default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: chantes

test:
  <<: *default
  database: chantes-test

production:
  <<: *default
  database: chantes-production
